Api, tests.
java-park-mail-ru/maze-09-2016 pull request #1
Opened 2016-10-04 19:36 UTC by kirrok

<3 java

2016-10-05 14:38 UTC, KSolovyev commented on .gitignore
> +.idea/mongoSettings.xml
Нет монго плагина у нас, убираем

2016-10-05 14:38 UTC, KSolovyev commented on .gitignore
> +*.iws
этого тоже нет

2016-10-05 14:38 UTC, KSolovyev commented on .gitignore
> +.mtj.tmp/
j2me тоже нет

2016-10-05 14:38 UTC, KSolovyev commented on README.md
> +   ### API (idk why curls from swagger-ui broken)
есть сайты, куда можно загрузить свое API. Попробуйте, может стать лучше

2016-10-05 14:38 UTC, KSolovyev commented on src/main/java/ru/mail/park/exceptions/ExceptionHandlerAdvice.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
Не, не, не. Сообщение об ошибке можно только админам показывать. Не надо провоцировать людей =)

2016-10-05 14:38 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            throw new CustomException(HttpStatus.BAD_REQUEST, validator.validationStatusAsJson());
Это называется exception-driven development  и считается антипатерном. Вы бросаете исключение, но на самом деле ничего плохого не случилось, просто пользователь попробовал взять уже занятое имя. Верните в этом месте ему ответ. Исключение надо кидать, когда вы не знаете контекст в котором исполняется метод и соответственно не можете разрешить проблему.
Кроме того передача управления через исключение в 70 раз медленнее, чем условный переход.

2016-10-05 14:38 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/Validator.java
> +public final class Validator {
Вместо этого нужно подключить spring-validation и добавить аннотации на поля объектов запросов.

2016-10-05 14:38 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/Validator.java
> +public final class Validator {
http://www.leveluplunch.com/java/tutorials/017-validate-spring-rest-webservice-request/

2016-10-05 14:38 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        final Validator validator = new Validator(login, password, email);
Если хотите красивую валидацию, то давайте попробуем, как я уже писал, spring-validation

2016-10-05 15:55 UTC, slavyanskii commented on src/main/java/ru/mail/park/exceptions/ExceptionHandlerAdvice.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
Т.е. оставить этот ExceptionHandler можно, но сообщение об ошибки сделать что-то типа "error" ?

2016-10-05 15:56 UTC, slavyanskii commented on README.md
> +   ### API (idk why curls from swagger-ui broken)
Уже все работает по прошлому урлу.

2016-10-05 15:56 UTC, slavyanskii commented on .gitignore
> +.mtj.tmp/
это было добавлено gitignore плагином для idea, как и прошлое - хорошо уберем.

2016-10-05 16:03 UTC, KSolovyev commented on README.md
> +   ### API (idk why curls from swagger-ui broken)
у меня есть пожелание, можно в апи поменять местами запрос и ответ? (те чтобы сначала был запрос, а потом ответ)

2016-10-05 16:04 UTC, KSolovyev commented on src/main/java/ru/mail/park/exceptions/ExceptionHandlerAdvice.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
по хорошему админу надо сказать ошибка: и дальше вывалить стек трейс. Но система прав не входит в курс. Так что просто покажите сообщение о том, что на сервере что-то пошло не так

2016-10-05 16:08 UTC, KSolovyev requested changes

2016-10-05 16:08 UTC, KSolovyev commented on tp_jave_new.xml
> +  <inspection_tool class="AbstractClassNamingConvention" enabled="true" level="WARNING" enabled_by_default="true">
Этот файл нужно удалить. Если вы его уже импортировали, то он больше не нужен

2016-10-05 16:08 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            throw new CustomException(HttpStatus.CONFLICT, "User already exists.");
И еще одно: Конфликт - это очень редкий код. В Http он используется, когда конфликтуют два параллельных запроса. Предлагаю никого не путать и попытаться подобрать другой код.

2016-10-05 16:17 UTC, kirrok commented on tp_jave_new.xml
> +  <inspection_tool class="AbstractClassNamingConvention" enabled="true" level="WARNING" enabled_by_default="true">
весь файл tp_java_new.lml?

2016-10-05 16:30 UTC, kirrok commented on src/main/java/ru/mail/park/main/Validator.java
> +public final class Validator {
Сейчас мы возвращаем клиенту в формате Json информацию о том какие именно поля не прошли валидацию. Клиент может распарсить и получить информацию о валидности каждого поля. Spring валидация, как я понял , возвращает длинное сообщение "Could not read Json..... информация о валидности полей". Клиент поймет лишь что какие то данные не валидны. Но ему же нужно знать какие именно. Или есть в сприновской валидации нужный функционал?

2016-10-05 18:52 UTC, slavyanskii commented on README.md
> +   ### API (idk why curls from swagger-ui broken)
К сожалению не нашёл такой кастомизации. Даже в петсторе http://petstore.swagger.io/#!/pet/uploadFile который показательный - все также, сначала ответ, потом запрос.

2016-10-05 22:55 UTC, KSolovyev commented on README.md
> +   ### API (idk why curls from swagger-ui broken)
Ну и ладно

2016-10-05 23:09 UTC, KSolovyev commented on tp_jave_new.xml
> +  <inspection_tool class="AbstractClassNamingConvention" enabled="true" level="WARNING" enabled_by_default="true">
да, это просто файл, он после импорта нигде идеей не используется

2016-10-06 10:02 UTC, KSolovyev requested changes

2016-10-06 10:02 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("invalid");
Во первых это невалидный json
Во вторых давайте откажемся от передачи захардкоженных сообщений через API.

2016-10-06 10:02 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("invalid");
Кроме того в спеке у вас написано, что вы ничего не возвращаете

2016-10-06 11:44 UTC, KSolovyev approved these changes

2016-10-06 12:14 UTC, merged